### PR TITLE
Bearer Token expiring Fix

### PR DESCRIPTION
**Pull request by j-oflaherty**
# Description of change
To go around issue #35 the code has been modified to updated the refresh token every 45, even if it has not expired. We weren't able to make the backoff on exception decorator work. 

# Manual QA steps
 - 
 
# Risks
 
# Rollback steps
 - revert this branch

### CODE REVIEW

**Comment by cmerrick** [comment]
Hi @j-oflaherty, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

**Comment by cmerrick** [comment]
You did it @j-oflaherty!

Thank you for signing the Singer Contribution License Agreement.

**Comment by tomaspinho** [comment]
Can we get this merged @cmerrick ? :smile: 

I'm trying to tap from a huge Asana organization and this is a huge blocker. I will try to use @j-oflaherty 's fork while a fix is not in `master`.

Thanks a ton for the tap and fix, both of you!

**Comment by tomaspinho** [comment]
Hello, any news on this? I have further stability improvements in my fork built on this one, but would prefer getting this one merged before I open a PR with mine. Thank you! cc @cmerrick

**Comment by j-oflaherty** [comment]
Hi, any updates @cmerrick? If @tomaspinho has further improved this version I don't have a problem with closing this PR if a better one is going to be opened.

**Comment by rdeshmukh15** [comment]
@j-oflaherty: Are you still facing the https://github.com/singer-io/tap-asana/issues/35 issue as I can see a fix has been provided for the same in PR https://github.com/singer-io/tap-asana/pull/41 and it is merged to master.

**Pull request closed without merging**
